AWS_GLUE_JOBS_NAME: ["<AWS_GLUE_JOB>"]
AWS_EC2_KEY_PAIR: "./airflow/dags/<KEY_FILE_PATH>"
AWS_EC2_HOSE_NAME: "<EC2_HOST>"
AWS_EC2_USER: "ec2-user"
AWS_EC2_CONDA_ENV_NAME: ec2
AWS_EC2_BASE_DIR: "<BASE_DIR_IN_EC2>"
AWS_EC2_ETL_FILES: ["<ETL_FILe_IN_EC2>"]
